name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
        with:
          python-version: '3.8'
      - name: Run tests
        run: scripts/test.sh

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
        with:
          python-version: '3.8'
      - name: Build executable
        run: scripts/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-mixtaper
          path: dist/
          if-no-files-found: error
